# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
parchment_version=1.21.5:2025.06.15
loader_version=0.17.3

# Mod Properties
mod_version=2.8.3
maven_group=red.jackf
archives_base_name=chesttracker

# Dependencies
bundle_searchables=true
searchables_version=1.21.5:1.0.3

# Mod Compat
clothconfig_version=18.0.145
shulkerboxtooltip_version=5.2.6+1.21.5
wthit_version=fabric-15.0.3
badpackets_version=fabric-0.8.2
jade_version=18.2.0+fabric
yacl_version=3.7.1+1.21.5-fabric
litematica_version=0.22.4
malilib_version=0.24.3

# JF_AUTO_UPDATE_BLOCK
fabric-api_version=0.128.2+1.21.5
modmenu_version=14.0.2
where-is-it_version=2.7.4+1.21.5
emi_version=1.1.12+1.21
# JF_END_AUTO_UPDATE_BLOCK

# Publishing
game_versions_mr=1.21.5
game_versions_curse=1.21.5

prefix=[1.21.5]
release_type=release
changelog_filter=[feat],[fix],[change],[update],[docs],[translations]
mod_name=Chest Tracker (Unofficial port)
github_owner=ponuing
github_repo=ChestTracker
github_url=https://github.com/ponuing/ChestTracker
